# Generated by Django 4.2.9 on 2024-01-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='', error_messages={'required': 'Role must be provided'}, max_length=12),
            preserve_default=False,
        ),
    ]
